version: '3'
services:
 
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ursa.vn/laravel_template
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html/
      - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network
    depends_on:
      - db
 
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
 
  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: laravel_template
      MYSQL_ROOT_PASSWORD: t7yoKyAfcm
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
 
#Docker Networks
networks:
  app-network:
    driver: bridge
    
#Volumes
volumes:
  dbdata:
    driver: local